image: drewcarlson/docker-android

variables:
  SIGNING_KEY: /builds/breadwallet/breadwallet-android/FakeSigningKey
  SIGNING_PASSWORD: qwerty
  SIGNING_ALIAS: key0
  SIGNING_ALIAS_PASSWORD: qwerty
  NATIVE_REVIEW_URL: https://breadwallet.gitlab.io/-/native-wallet-review/-/jobs/484039874/artifacts/build/distributions/index.html

before_script:
  - git submodule sync
  - git submodule update --init --force --remote

cache:
  key: ${CI_PROJECT_ID}-2
  paths:
    - ~/.gradle/
    - /root/.gradle/

detekt:
  stage: build
  script:
    - ./gradlew --console=plain detekt
  only:
    - merge_requests
  artifacts:
    expose_as: "Detekt Report"
    paths:
      - app/build/reports/detekt/detekt.html

debug:test:
  stage: build
  script:
    - ./gradlew --console=plain testBrdDebugUnitTest testBrdTestnetDebugUnitTest
  only:
    - develop
    - master
    - /^release.*$/
    - merge_requests
  artifacts:
    reports:
      junit: app/build/test-results/**/TEST-*.xml

testnet:debug:build-deploy:
  stage: build
  script:
    - fastlane appetizeUpload flavor:brdTestnet build_type:debug
  only:
    - develop
    - master
    - /^release.*$/
    - merge_requests
  artifacts:
    expose_as: "Review Testnet"
    paths:
      - app/build/review-brdTestnet-debug.html

mainnet:debug:build-deploy:
  stage: build
  script:
    - fastlane appetizeUpload flavor:brd build_type:debug
  only:
    - develop
    - master
    - /^release.*$/
    - merge_requests
  artifacts:
    expose_as: "Review Mainnet"
    paths:
      - app/build/review-brd-debug.html

release:test:
  stage: build
  script:
    - ./gradlew --console=plain testBrdReleaseUnitTest testBrdTestnetReleaseUnitTest
  only:
    - develop
    - master
    - /^release.*$/
    - merge_requests
  artifacts:
    reports:
      junit: app/build/test-results/**/TEST-*.xml

release:build-deploy:
  stage: build
  script:
    - ./gradlew --console=plain assembleRelease appDistributionUploadBrdRelease
    - fastlane appetizeUpload flavor:brd build_type:release
    - fastlane appetizeUpload flavor:brdTestnet build_type:release
  only:
    - develop
    - master
    - /^release.*$/
  artifacts:
    paths:
      - app/build/outputs/apk/
      - app/build/review-brd-release.html
      - app/build/review-brdTestnet-release.html
